#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MMD_Android.Resource", IsApplication=true)]

namespace MMD_Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fadein = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fadeout = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int slide_in_left = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int slide_in_right = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int slide_out_left = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int slide_out_right = 2130968581;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int happy = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int monoandroidsplash = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int FacebookButton = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int FacebookButtonNoCancel = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int button_Categories = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int button_Friends = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int button_Groups = 2131165193;
			
			// aapt resource value: 0x7f07000d
			public const int button_Login = 2131165197;
			
			// aapt resource value: 0x7f07000a
			public const int button_Memoticons = 2131165194;
			
			// aapt resource value: 0x7f070007
			public const int button_Messages = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int button_Miki = 2131165189;
			
			// aapt resource value: 0x7f07000e
			public const int button_Signup = 2131165198;
			
			// aapt resource value: 0x7f070004
			public const int button_Veres = 2131165188;
			
			// aapt resource value: 0x7f07000f
			public const int editText1 = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int editText2 = 2131165200;
			
			// aapt resource value: 0x7f07000b
			public const int email_input_field = 2131165195;
			
			// aapt resource value: 0x7f070002
			public const int imageView1 = 2131165186;
			
			// aapt resource value: 0x7f07000c
			public const int password_input_field = 2131165196;
			
			// aapt resource value: 0x7f070003
			public const int textView_Username = 2131165187;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Bogdan = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Home = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LoginSignup = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Miki = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int NewA = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int Categories = 2131034116;
			
			// aapt resource value: 0x7f05000c
			public const int Facebook = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int FacebookNoCancel = 2131034125;
			
			// aapt resource value: 0x7f050006
			public const int Friends = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int Groups = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int Login = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int Memoticons = 2131034120;
			
			// aapt resource value: 0x7f050005
			public const int Messages = 2131034117;
			
			// aapt resource value: 0x7f05000b
			public const int Miki = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int Settings = 2131034121;
			
			// aapt resource value: 0x7f050003
			public const int Signup = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int Veres = 2131034122;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
