#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ArcMenuLib.Resource", IsApplication=true)]

namespace ArcMenuLib
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int childSize = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int fromDegrees = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int leftHolderWidth = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int toDegrees = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int composer_button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int composer_button_normal = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int composer_button_pressed = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int composer_icn_plus = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int composer_icn_plus_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int composer_icn_plus_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int monoandroidsplash = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int MyButton = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int control_hint = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int control_layout = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int item_layout = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int arc_menu = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ray_menu = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ArcLayout = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int ArcLayout_childSize = 2;
			
			// aapt resource value: 0
			public const int ArcLayout_fromDegrees = 0;
			
			// aapt resource value: 1
			public const int ArcLayout_toDegrees = 1;
			
			public static int[] ArcMenu = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int ArcMenu_childSize = 2;
			
			// aapt resource value: 0
			public const int ArcMenu_fromDegrees = 0;
			
			// aapt resource value: 1
			public const int ArcMenu_toDegrees = 1;
			
			public static int[] RayLayout = new int[] {
					2130771971};
			
			// aapt resource value: 0
			public const int RayLayout_leftHolderWidth = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
