#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ArcMenuTestApp.Resource", IsApplication=true)]

namespace ArcMenuTestApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::arcmenulib.Resource.Attribute.childSize = global::ArcMenuTestApp.Resource.Attribute.childSize;
			global::arcmenulib.Resource.Attribute.fromDegrees = global::ArcMenuTestApp.Resource.Attribute.fromDegrees;
			global::arcmenulib.Resource.Attribute.leftHolderWidth = global::ArcMenuTestApp.Resource.Attribute.leftHolderWidth;
			global::arcmenulib.Resource.Attribute.toDegrees = global::ArcMenuTestApp.Resource.Attribute.toDegrees;
			global::arcmenulib.Resource.Drawable.composer_button = global::ArcMenuTestApp.Resource.Drawable.composer_button;
			global::arcmenulib.Resource.Drawable.composer_button_normal = global::ArcMenuTestApp.Resource.Drawable.composer_button_normal;
			global::arcmenulib.Resource.Drawable.composer_button_pressed = global::ArcMenuTestApp.Resource.Drawable.composer_button_pressed;
			global::arcmenulib.Resource.Drawable.composer_icn_plus = global::ArcMenuTestApp.Resource.Drawable.composer_icn_plus;
			global::arcmenulib.Resource.Drawable.composer_icn_plus_normal = global::ArcMenuTestApp.Resource.Drawable.composer_icn_plus_normal;
			global::arcmenulib.Resource.Drawable.composer_icn_plus_pressed = global::ArcMenuTestApp.Resource.Drawable.composer_icn_plus_pressed;
			global::arcmenulib.Resource.Drawable.Icon = global::ArcMenuTestApp.Resource.Drawable.Icon;
			global::arcmenulib.Resource.Id.control_hint = global::ArcMenuTestApp.Resource.Id.control_hint;
			global::arcmenulib.Resource.Id.control_layout = global::ArcMenuTestApp.Resource.Id.control_layout;
			global::arcmenulib.Resource.Id.item_layout = global::ArcMenuTestApp.Resource.Id.item_layout;
			global::arcmenulib.Resource.Layout.arc_menu = global::ArcMenuTestApp.Resource.Layout.arc_menu;
			global::arcmenulib.Resource.Layout.ray_menu = global::ArcMenuTestApp.Resource.Layout.ray_menu;
			global::arcmenulib.Resource.String.ApplicationName = global::ArcMenuTestApp.Resource.String.ApplicationName;
			global::arcmenulib.Resource.String.Hello = global::ArcMenuTestApp.Resource.String.Hello;
			global::arcmenulib.Resource.Styleable.ArcLayout = global::ArcMenuTestApp.Resource.Styleable.ArcLayout;
			global::arcmenulib.Resource.Styleable.ArcLayout_childSize = global::ArcMenuTestApp.Resource.Styleable.ArcLayout_childSize;
			global::arcmenulib.Resource.Styleable.ArcLayout_fromDegrees = global::ArcMenuTestApp.Resource.Styleable.ArcLayout_fromDegrees;
			global::arcmenulib.Resource.Styleable.ArcLayout_toDegrees = global::ArcMenuTestApp.Resource.Styleable.ArcLayout_toDegrees;
			global::arcmenulib.Resource.Styleable.ArcMenu = global::ArcMenuTestApp.Resource.Styleable.ArcMenu;
			global::arcmenulib.Resource.Styleable.ArcMenu_childSize = global::ArcMenuTestApp.Resource.Styleable.ArcMenu_childSize;
			global::arcmenulib.Resource.Styleable.ArcMenu_fromDegrees = global::ArcMenuTestApp.Resource.Styleable.ArcMenu_fromDegrees;
			global::arcmenulib.Resource.Styleable.ArcMenu_toDegrees = global::ArcMenuTestApp.Resource.Styleable.ArcMenu_toDegrees;
			global::arcmenulib.Resource.Styleable.RayLayout = global::ArcMenuTestApp.Resource.Styleable.RayLayout;
			global::arcmenulib.Resource.Styleable.RayLayout_leftHolderWidth = global::ArcMenuTestApp.Resource.Styleable.RayLayout_leftHolderWidth;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int childSize = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int fromDegrees = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int leftHolderWidth = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int toDegrees = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050002
			public const int menuChildSize = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int menuFromDegrees = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int menuToDegrees = 2131034113;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int composer_button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int composer_button_normal = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int composer_button_pressed = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int composer_camera = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int composer_icn_plus = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int composer_icn_plus_normal = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int composer_icn_plus_pressed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int composer_music = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int composer_place = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int composer_sleep = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int composer_thought = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int composer_with = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_launcher = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Icon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int monoandroidsplash = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070003
			public const int arc_menu3 = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int arc_menu_2 = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int control_hint = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int control_layout = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int item_layout = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int arc_menu = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ray_menu = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ArcLayout = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int ArcLayout_childSize = 2;
			
			// aapt resource value: 0
			public const int ArcLayout_fromDegrees = 0;
			
			// aapt resource value: 1
			public const int ArcLayout_toDegrees = 1;
			
			public static int[] ArcMenu = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int ArcMenu_childSize = 2;
			
			// aapt resource value: 0
			public const int ArcMenu_fromDegrees = 0;
			
			// aapt resource value: 1
			public const int ArcMenu_toDegrees = 1;
			
			public static int[] RayLayout = new int[] {
					2130771971};
			
			// aapt resource value: 0
			public const int RayLayout_leftHolderWidth = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
